#!/usr/bin/bash

FILENAMES="black_king_glow black_king_angry black_king_cry black_king_smile black_queen_base_glow black_queen_angry black_queen_annoyed black_queen_cry black_queen_grimace black_queen_laugh black_queen_normal black_bishop_glow black_bishop_angry black_bishop_cry black_bishop_normal black_bishop_shocked black_knight_glow black_knight_angry black_knight_cry black_knight_shocked black_knight_wink white_king_glow white_king_angry white_king_blackline white_king_embarrassed white_king_glow white_king_laugh white_king_shocked white_king_smile white_king_soybean white_king_wink white_queen_glow white_queen_fan_glow white_queen_angry white_queen_loading white_queen_shocked white_queen_soybean white_queen_speechless white_queen_wink white_bishop_glow white_bishop_angry white_bishop_cry white_bishop_normal white_bishop_shocked white_knight_glow white_knight_angry white_knight_cry white_knight_shocked white_knight_wink"

for file in $FILENAMES; do
    python ./png2webp.py $file.png $file.webp
done
